### ISSUE TITLE
Add MFA login

### ISSUE THREAD

**Issue by Luzifer** [awesomecoders/cloudkeys#12]
As a user of a cloudkeys instance I want my password stores with passwords and data with higher security requirements to be only accessible after a multi factor auth token has been entered to ensure even a key logger which got access to my login and master password is not able to open the password database.

**Comment by mthie** [comment]
What about this solution: https://github.com/PHPGangsta/GoogleAuthenticator

**Comment by Luzifer** [comment]
Yep. Exactly that. Just need to implement this.
